/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authVerifyRouteImport } from './routes/(auth)/verify'
import { Route as AppAllRouteImport } from './routes/app/all'
import { Route as AppRecommendRouteImport } from './routes/app/recommend'
import { Route as AppStudyCardIndexRouteImport } from './routes/app/study-card/index'
import { Route as AppStudyCardSci_idSectionIndexRouteImport } from './routes/app/study-card/$sci_id/$section/index'
import { Route as AppStudyCardSci_idSectionQuizsIndexRouteImport } from './routes/app/study-card/$sci_id/$section/$quizs/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyRoute = authVerifyRouteImport.update({
  id: '/(auth)/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAllRoute = AppAllRouteImport.update({
  id: '/app/all',
  path: '/app/all',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecommendRoute = AppRecommendRouteImport.update({
  id: '/app/recommend',
  path: '/app/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyCardIndexRoute = AppStudyCardIndexRouteImport.update({
  id: '/app/study-card/',
  path: '/app/study-card/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudyCardSci_idSectionIndexRoute =
  AppStudyCardSci_idSectionIndexRouteImport.update({
    id: '/app/study-card/$sci_id/$section/',
    path: '/app/study-card/$sci_id/$section/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppStudyCardSci_idSectionQuizsIndexRoute =
  AppStudyCardSci_idSectionQuizsIndexRouteImport.update({
    id: '/app/study-card/$sci_id/$section/$quizs/',
    path: '/app/study-card/$sci_id/$section/$quizs/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify': typeof authVerifyRoute
  '/app/all': typeof AppAllRoute
  '/app/recommend': typeof AppRecommendRoute
  '/app/study-card/': typeof AppStudyCardIndexRoute
  '/app/study-card/$sci_id/$section/': typeof AppStudyCardSci_idSectionIndexRoute
  '/app/study-card/$sci_id/$section/$quizs/': typeof AppStudyCardSci_idSectionQuizsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/verify': typeof authVerifyRoute
  '/app/all': typeof AppAllRoute
  '/app/recommend': typeof AppRecommendRoute
  '/app/study-card': typeof AppStudyCardIndexRoute
  '/app/study-card/$sci_id/$section': typeof AppStudyCardSci_idSectionIndexRoute
  '/app/study-card/$sci_id/$section/$quizs': typeof AppStudyCardSci_idSectionQuizsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify': typeof authVerifyRoute
  '/app/all': typeof AppAllRoute
  '/app/recommend': typeof AppRecommendRoute
  '/app/study-card/': typeof AppStudyCardIndexRoute
  '/app/study-card/$sci_id/$section/': typeof AppStudyCardSci_idSectionIndexRoute
  '/app/study-card/$sci_id/$section/$quizs/': typeof AppStudyCardSci_idSectionQuizsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/verify'
    | '/app/all'
    | '/app/recommend'
    | '/app/study-card/'
    | '/app/study-card/$sci_id/$section/'
    | '/app/study-card/$sci_id/$section/$quizs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/verify'
    | '/app/all'
    | '/app/recommend'
    | '/app/study-card'
    | '/app/study-card/$sci_id/$section'
    | '/app/study-card/$sci_id/$section/$quizs'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(auth)/verify'
    | '/app/all'
    | '/app/recommend'
    | '/app/study-card/'
    | '/app/study-card/$sci_id/$section/'
    | '/app/study-card/$sci_id/$section/$quizs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyRoute: typeof authVerifyRoute
  AppAllRoute: typeof AppAllRoute
  AppRecommendRoute: typeof AppRecommendRoute
  AppStudyCardIndexRoute: typeof AppStudyCardIndexRoute
  AppStudyCardSci_idSectionIndexRoute: typeof AppStudyCardSci_idSectionIndexRoute
  AppStudyCardSci_idSectionQuizsIndexRoute: typeof AppStudyCardSci_idSectionQuizsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify': {
      id: '/(auth)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/all': {
      id: '/app/all'
      path: '/app/all'
      fullPath: '/app/all'
      preLoaderRoute: typeof AppAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/recommend': {
      id: '/app/recommend'
      path: '/app/recommend'
      fullPath: '/app/recommend'
      preLoaderRoute: typeof AppRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/study-card/': {
      id: '/app/study-card/'
      path: '/app/study-card'
      fullPath: '/app/study-card/'
      preLoaderRoute: typeof AppStudyCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/study-card/$sci_id/$section/': {
      id: '/app/study-card/$sci_id/$section/'
      path: '/app/study-card/$sci_id/$section'
      fullPath: '/app/study-card/$sci_id/$section/'
      preLoaderRoute: typeof AppStudyCardSci_idSectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/study-card/$sci_id/$section/$quizs/': {
      id: '/app/study-card/$sci_id/$section/$quizs/'
      path: '/app/study-card/$sci_id/$section/$quizs'
      fullPath: '/app/study-card/$sci_id/$section/$quizs/'
      preLoaderRoute: typeof AppStudyCardSci_idSectionQuizsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  authVerifyRoute: authVerifyRoute,
  AppAllRoute: AppAllRoute,
  AppRecommendRoute: AppRecommendRoute,
  AppStudyCardIndexRoute: AppStudyCardIndexRoute,
  AppStudyCardSci_idSectionIndexRoute: AppStudyCardSci_idSectionIndexRoute,
  AppStudyCardSci_idSectionQuizsIndexRoute:
    AppStudyCardSci_idSectionQuizsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
